In [1]:
using LinearAlgebra

"""
    factorizacion_lu_doolittle(A)

Calcula la factorización LU de una matriz cuadrada A (A = LU) utilizando el
método de Doolittle, donde la matriz L tiene unos en su diagonal.

# Argumentos
- `A::Matrix{Float64}`: La matriz cuadrada n x n a factorizar.

# Retorna
- `(L, U)`: Una tupla conteniendo las matrices L (triangular inferior) y U
  (triangular superior).
- `nothing`: Si la factorización no es posible (un pivote es cero).
"""
function factorizacion_lu_doolittle(A::Matrix{Float64})
    n = size(A, 1)
    if size(A, 2) != n
        error("La matriz de entrada debe ser cuadrada.")
    end

    L = Matrix{Float64}(I, n, n) # Matriz identidad para L (l_ii = 1)
    U = zeros(Float64, n, n)    # Matriz de ceros para U

    # Bucle principal que combina los pasos del algoritmo
    for i in 1:n
        # --- Cálculo de la fila i de U ---
        # Corresponde a Pasos 1, 4, 5 y 6 para U
        for j in i:n
            suma = dot(L[i, 1:(i-1)], U[1:(i-1), j])
            U[i, j] = A[i, j] - suma
        end

        # --- Verificación de Pivote ---
        # Implícito en Pasos 1, 4 y 6
        if U[i, i] == 0
            println("Factorización imposible: se encontró un pivote cero en la posición ($i, $i).")
            # El Paso 6 nota que si U[n,n]==0, A es singular.
            if i == n
                 println("La matriz A es singular.")
            end
            return nothing # SALIDA
        end

        # --- Cálculo de la columna i de L ---
        # Corresponde a Pasos 2 y 5 para L
        if i < n
            for j in (i+1):n
                suma = dot(L[j, 1:(i-1)], U[1:(i-1), i])
                L[j, i] = (A[j, i] - suma) / U[i, i]
            end
        end
    end

    # Paso 7: Devolver las matrices L y U
    println("Procedimiento completado con éxito.")
    return (L, U)
end

factorizacion_lu_doolittle

In [2]:
# Matriz de entrada
A = [2.0 1.0 -1.0;
     -3.0 -1.0 2.0;
     -2.0 1.0 2.0]

println("--- Factorización LU de la Matriz A ---")
println("Matriz A:")
display(A)
println()

# Llamamos a la función
resultado = factorizacion_lu_doolittle(A)

# Imprimimos los resultados si la factorización fue exitosa
if resultado !== nothing
    L, U = resultado
    
    println("\nMatriz L (Triangular Inferior):")
    display(L)
    
    println("\nMatriz U (Triangular Superior):")
    display(U)
    
    # Verificación: L * U debe ser igual a A
    println("\n--- Verificación: L * U ---")
    A_reconstruida = L * U
    display(A_reconstruida)
    
    # Comprobamos si son aproximadamente iguales
    if isapprox(A, A_reconstruida)
        println("\n✅ Verificación exitosa: L * U es igual a A.")
    else
        println("\n❌ Error: L * U no es igual a A.")
    end
end

--- Factorización LU de la Matriz A ---
Matriz A:


3×3 Matrix{Float64}:
  2.0   1.0  -1.0
 -3.0  -1.0   2.0
 -2.0   1.0   2.0


Procedimiento completado con éxito.

Matriz L (Triangular Inferior):


3×3 Matrix{Float64}:
  1.0  0.0  0.0
 -1.5  1.0  0.0
 -1.0  4.0  1.0


Matriz U (Triangular Superior):


3×3 Matrix{Float64}:
 2.0  1.0  -1.0
 0.0  0.5   0.5
 0.0  0.0  -1.0


--- Verificación: L * U ---


3×3 Matrix{Float64}:
  2.0   1.0  -1.0
 -3.0  -1.0   2.0
 -2.0   1.0   2.0


✅ Verificación exitosa: L * U es igual a A.
