In [1]:
using LinearAlgebra

"""
    factorizacion_cholesky(A)

Calcula la factorización de Cholesky de una matriz simétrica y definida
positiva A, tal que A = L * L', donde L es una matriz triangular inferior.

# Argumentos
- `A::Matrix{Float64}`: La matriz cuadrada n x n a factorizar.

# Retorna
- `L::Matrix{Float64}`: La matriz triangular inferior L.
- Lanza un error si la matriz no es simétrica o no es definida positiva.
"""
function factorizacion_cholesky(A::Matrix{Float64})
    n = size(A, 1)
    if size(A, 2) != n
        error("La matriz de entrada debe ser cuadrada.")
    end
    if !issymmetric(A)
        error("La matriz de entrada no es simétrica.")
    end

    L = zeros(Float64, n, n)
    println("--- Iniciando Factorización de Cholesky ---")

    # Paso 1: Calcular l₁₁
    if A[1, 1] <= 0
        error("La matriz no es definida positiva (A[1,1] <= 0).")
    end
    L[1, 1] = sqrt(A[1, 1])

    # Paso 2: Calcular la primera columna de L
    for j in 2:n
        L[j, 1] = A[j, 1] / L[1, 1]
    end

    # Paso 3: Bucle principal para las columnas 2 hasta n-1
    for i in 2:(n-1)
        # Paso 4: Calcular los elementos de la diagonal lᵢᵢ
        suma_cuadrados = dot(L[i, 1:(i-1)], L[i, 1:(i-1)]) # Suma de lᵢₖ²
        termino_sqrt = A[i, i] - suma_cuadrados
        if termino_sqrt <= 0
            error("La matriz no es definida positiva (término no positivo en la diagonal $i).")
        end
        L[i, i] = sqrt(termino_sqrt)

        # Paso 5: Calcular los elementos debajo de la diagonal lⱼᵢ
        for j in (i+1):n
            suma_productos = dot(L[j, 1:(i-1)], L[i, 1:(i-1)]) # Suma de lⱼₖ * lᵢₖ
            L[j, i] = (A[j, i] - suma_productos) / L[i, i]
        end
    end

    # Paso 6: Calcular el último elemento de la diagonal lₙₙ
    if n > 1
        suma_cuadrados_final = dot(L[n, 1:(n-1)], L[n, 1:(n-1)])
        termino_sqrt_final = A[n, n] - suma_cuadrados_final
        if termino_sqrt_final <= 0
            error("La matriz no es definida positiva (término no positivo en la diagonal $n).")
        end
        L[n, n] = sqrt(termino_sqrt_final)
    end

    # Paso 7: Devolver la matriz L
    println("Factorización completada con éxito.")
    return L
end

factorizacion_cholesky

In [2]:
# Matriz de entrada simétrica y definida positiva
A = [ 4.0  12.0  -16.0;
     12.0  37.0  -43.0;
    -16.0 -43.0   98.0]

println("Matriz A:")
display(A)
println()

# Llamamos a la función
try
    L = factorizacion_cholesky(A)
    
    println("\nMatriz L resultante:")
    display(L)
    
    # Verificación: L * L' debe ser igual a A
    println("\n--- Verificación: L * L' ---")
    A_reconstruida = L * L'
    display(A_reconstruida)
    
    if isapprox(A, A_reconstruida)
        println("\n✅ Verificación exitosa: L * L' es igual a A.")
    else
        println("\n❌ Error: L * L' no es igual a A.")
    end
catch e
    println(e)
end

Matriz A:


3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0


--- Iniciando Factorización de Cholesky ---
Factorización completada con éxito.

Matriz L resultante:


3×3 Matrix{Float64}:
  2.0  0.0  0.0
  6.0  1.0  0.0
 -8.0  5.0  3.0


--- Verificación: L * L' ---


3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0


✅ Verificación exitosa: L * L' es igual a A.
