In [1]:
using LinearAlgebra

"""
    metodo_jacobi(A, b, x0; tol=1e-5, max_iter=100)

Resuelve el sistema de ecuaciones lineales Ax = b utilizando el método
iterativo de Jacobi, a partir de una aproximación inicial x0.

# Argumentos
- `A::Matrix{Float64}`: Matriz de coeficientes n x n.
- `b::Vector{Float64}`: Vector de términos independientes.
- `x0::Vector{Float64}`: Vector de aproximación inicial.

# Argumentos Opcionales
- `tol::Float64`: Tolerancia para el criterio de convergencia.
- `max_iter::Int`: Número máximo de iteraciones permitidas.

# Retorna
- `Vector{Float64}`: El vector de solución `x`, o la última aproximación si no converge.
"""
function metodo_jacobi(A::Matrix{Float64}, b::Vector{Float64}, x0::Vector{Float64}; 
                         tol::Float64=1e-5, max_iter::Int=100)
    
    n = size(A, 1)
    
    # Verificación: los elementos de la diagonal no pueden ser cero
    if any(isapprox.(diag(A), 0))
        error("Se encontró un cero en la diagonal. El método de Jacobi no es aplicable.")
    end

    # Hacemos copias para no modificar los vectores originales
    xo = copy(x0) # Vector de la iteración anterior (XO en el pseudocódigo)
    x = zeros(n)  # Vector para la nueva iteración

    println("--- Iniciando Método de Jacobi ---")
    
    # Paso 1: Inicializar el contador de iteraciones
    k = 1
    
    # Paso 2: Bucle principal de iteraciones
    while k <= max_iter
        # Paso 3: Calcular cada componente de la nueva aproximación 'x'
        for i in 1:n
            # Sumatoria de aᵢⱼ * xoⱼ para j ≠ i
            suma = dot(A[i, :], xo) - A[i, i] * xo[i]
            
            x[i] = (b[i] - suma) / A[i, i]
        end
        
        # Paso 4: Criterio de convergencia
        # Usamos la norma euclidiana (norma 2) para medir la diferencia
        error_estimado = norm(x - xo)
        println("Iteración $k: Error = $error_estimado")
        
        if error_estimado < tol
            println("\nProcedimiento exitoso: Convergencia alcanzada en $k iteraciones.")
            return x # SALIDA
        end
        
        # Paso 5: Incrementar el contador
        k += 1
        
        # Paso 6: Actualizar el vector de la iteración anterior
        xo = copy(x)
    end
    
    # Paso 7: Mensaje si se excede el número de iteraciones
    println("\nProcedimiento no exitoso: Se excedió el número máximo de iteraciones ($max_iter).")
    return x # Devuelve la última aproximación calculada
end

metodo_jacobi

In [2]:
# Sistema de ecuaciones a resolver:
# 10x₁ -  x₂ + 2x₃ = 6
# -x₁ + 11x₂ -  x₃ + 3x₄ = 25
# 2x₁ -  x₂ + 10x₃ - x₄ = -11
#        3x₂ -  x₃ + 8x₄ = 15
# La solución real es x = [1, 2, -1, 1]

# Matriz de coeficientes (diagonalmente dominante)
A = [10.0 -1.0  2.0  0.0;
     -1.0 11.0 -1.0  3.0;
      2.0 -1.0 10.0 -1.0;
      0.0  3.0 -1.0  8.0]

# Vector de términos independientes
b = [6.0, 25.0, -11.0, 15.0]

# Aproximación inicial (un vector de ceros es una opción común)
x_inicial = [0.0, 0.0, 0.0, 0.0]

# Llamamos a la función
solucion = metodo_jacobi(A, b, x_inicial, tol=1e-7, max_iter=50)

println("\n--- Solución Aproximada ---")
display(round.(solucion, digits=5))


# --- Verificación ---
println("\n--- Verificación: A * x ---")
b_calculado = A * solucion
println("El resultado de A*x es (debería ser muy cercano a b):")
display(round.(b_calculado, digits=5))
println("\nEl vector b original es:")
display(b)

--- Iniciando Método de Jacobi ---
Iteración 1: Error = 3.201704898362488
Iteración 2: Error = 1.2556434177591917
Iteración 3: Error = 0.49690551414887585
Iteración 4: Error = 0.21908517016723458
Iteración 5: Error = 0.0897453205646945
Iteración 6: Error = 0.03927457310200121
Iteración 7: Error = 0.01632327649212992
Iteración 8: Error = 0.007087147155725602
Iteración 9: Error = 0.0029727990696921114
Iteración 10: Error = 0.0012831613556191068
Iteración 11: Error = 0.0005414124462409017
Iteración 12: Error = 0.00023274437316388725
Iteración 13: Error = 9.857302867787895e-5
Iteración 14: Error = 4.225903498243776e-5
Iteración 15: Error = 1.7940988927740493e-5
Iteración 16: Error = 7.677445137748676e-6
Iteración 17: Error = 3.2645209743118855e-6
Iteración 18: Error = 1.3952996108526328e-6
Iteración 19: Error = 5.93892451533809e-7
Iteración 20: Error = 2.536369044930509e-7
Iteración 21: Error = 1.0802811626213997e-7
Iteración 22: Error = 4.6112250733034134e-8

Procedimiento exitoso: Conver

4-element Vector{Float64}:
  1.0
  2.0
 -1.0
  1.0


--- Verificación: A * x ---
El resultado de A*x es (debería ser muy cercano a b):


4-element Vector{Float64}:
   6.0
  25.0
 -11.0
  15.0


El vector b original es:


4-element Vector{Float64}:
   6.0
  25.0
 -11.0
  15.0